name: infra setup practice
on:
  push:
    branches:
      - main
      - release/*
      - hotfix/*
    
jobs:
  
  my_shannu_id:
    name: sks first job
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
     - name: Checkout code
       uses: actions/checkout@v6.0.2
     - name: HashiCorp - Setup Terraform
       uses: hashicorp/setup-terraform@v2.0.3
     - name: terraform init
       run:  terraform init

  my_shannu2_id:
    name: sks 2nd job
    runs-on: windows-latest
    needs: my_shannu_id
    if: always()
    steps:
      - name: shannu
        run: write-host "windiws workflow for test"
